trading:
  symbols: 
    - ETHUSDT
  timeframe: 15m
  risk_usd: 100
  commission: 0.001
  spread: 0.0001
  historical_days: 260
  update_interval_sec: 60

binance:
  api_key: ""
  api_secret: ""
  testnet: true

telegram:
  token: ""
  chat_id: ""
