trading:
  symbols: 
    - DOGEUSDT
    - ETHUSDT
    - BTCUSDT
  timeframe: 5m
  risk_usd: 100
  commission: 0.001
  spread: 0.0001
  historical_days: 360
  update_interval_sec: 60

binance:
  api_key: "rQrrXDMCeYmFcjRDW1KKfGkwhLIyw3bP8kVrJ3UjGiCMfjPi8Y5Pe0VaF1VMsDYd"
  api_secret: "54gmFT7wLTZUa7yRlftgFHuTQsJvTOIhmjS5NRvcKovCloYQrfQ0FaRujRBHk1FJ"
  testnet: true

telegram:
  token: "7845225008:AAG86ydZRTucCHIYtrksBwq46O-FDazF5-8"
  chat_id: "6747158875"